"""Rev1

Revision ID: 435907f3aa35
Revises: 
Create Date: 2024-05-25 21:07:27.387209

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '435907f3aa35'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asset',
    sa.Column('path', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_asset_character_id'), 'asset', ['character_id'], unique=False)
    op.create_index(op.f('ix_asset_path'), 'asset', ['path'], unique=False)
    op.create_index(op.f('ix_asset_project_id'), 'asset', ['project_id'], unique=False)
    op.create_table('character',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('appearance', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('personality', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_character_appearance'), 'character', ['appearance'], unique=False)
    op.create_index(op.f('ix_character_name'), 'character', ['name'], unique=False)
    op.create_index(op.f('ix_character_personality'), 'character', ['personality'], unique=False)
    op.create_index(op.f('ix_character_project_id'), 'character', ['project_id'], unique=False)
    op.create_table('conceptart',
    sa.Column('image', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conceptart_entity_id'), 'conceptart', ['entity_id'], unique=False)
    op.create_index(op.f('ix_conceptart_image'), 'conceptart', ['image'], unique=False)
    op.create_index(op.f('ix_conceptart_project_id'), 'conceptart', ['project_id'], unique=False)
    op.create_table('dialog',
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('character1_id', sa.Integer(), nullable=False),
    sa.Column('character2_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('character1_goal', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('character2_goal', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dialog_character1_goal'), 'dialog', ['character1_goal'], unique=False)
    op.create_index(op.f('ix_dialog_character1_id'), 'dialog', ['character1_id'], unique=False)
    op.create_index(op.f('ix_dialog_character2_goal'), 'dialog', ['character2_goal'], unique=False)
    op.create_index(op.f('ix_dialog_character2_id'), 'dialog', ['character2_id'], unique=False)
    op.create_index(op.f('ix_dialog_project_id'), 'dialog', ['project_id'], unique=False)
    op.create_table('message',
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('author', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('dialog_id', sa.Integer(), nullable=False),
    sa.Column('index', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_message_author'), 'message', ['author'], unique=False)
    op.create_index(op.f('ix_message_content'), 'message', ['content'], unique=False)
    op.create_index(op.f('ix_message_dialog_id'), 'message', ['dialog_id'], unique=False)
    op.create_index(op.f('ix_message_index'), 'message', ['index'], unique=False)
    op.create_table('project',
    sa.Column('project_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('project_description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('image', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_image'), 'project', ['image'], unique=False)
    op.create_index(op.f('ix_project_project_description'), 'project', ['project_description'], unique=False)
    op.create_index(op.f('ix_project_project_name'), 'project', ['project_name'], unique=False)
    op.create_index(op.f('ix_project_user_id'), 'project', ['user_id'], unique=False)
    op.create_table('user',
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_password'), 'user', ['password'], unique=False)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_password'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_project_user_id'), table_name='project')
    op.drop_index(op.f('ix_project_project_name'), table_name='project')
    op.drop_index(op.f('ix_project_project_description'), table_name='project')
    op.drop_index(op.f('ix_project_image'), table_name='project')
    op.drop_table('project')
    op.drop_index(op.f('ix_message_index'), table_name='message')
    op.drop_index(op.f('ix_message_dialog_id'), table_name='message')
    op.drop_index(op.f('ix_message_content'), table_name='message')
    op.drop_index(op.f('ix_message_author'), table_name='message')
    op.drop_table('message')
    op.drop_index(op.f('ix_dialog_project_id'), table_name='dialog')
    op.drop_index(op.f('ix_dialog_character2_id'), table_name='dialog')
    op.drop_index(op.f('ix_dialog_character2_goal'), table_name='dialog')
    op.drop_index(op.f('ix_dialog_character1_id'), table_name='dialog')
    op.drop_index(op.f('ix_dialog_character1_goal'), table_name='dialog')
    op.drop_table('dialog')
    op.drop_index(op.f('ix_conceptart_project_id'), table_name='conceptart')
    op.drop_index(op.f('ix_conceptart_image'), table_name='conceptart')
    op.drop_index(op.f('ix_conceptart_entity_id'), table_name='conceptart')
    op.drop_table('conceptart')
    op.drop_index(op.f('ix_character_project_id'), table_name='character')
    op.drop_index(op.f('ix_character_personality'), table_name='character')
    op.drop_index(op.f('ix_character_name'), table_name='character')
    op.drop_index(op.f('ix_character_appearance'), table_name='character')
    op.drop_table('character')
    op.drop_index(op.f('ix_asset_project_id'), table_name='asset')
    op.drop_index(op.f('ix_asset_path'), table_name='asset')
    op.drop_index(op.f('ix_asset_character_id'), table_name='asset')
    op.drop_table('asset')
    # ### end Alembic commands ###
